# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tfk8HwI8GYW5rZAefN7Frkl0_YXngn3R
"""

class Model:
  def __init__(self):
    import requests
    import gdown
    url = 'https://drive.google.com/uc?export=download&id=1DXcj2-u5a5Ybir-YmRUnCaBLQN3NQSm-'
    output = 'modeloprueba2.h5'
    gdown.download(url, output, quiet=False)
    #r = requests.get('https://github.com/magomartin/Prueba_IA_CNN_clasificar_imagen/blob/main/my_model.h5?raw=true')  
    #with open('/content/mimodelo.h5', 'wb') as f:
     # f.write(r.content)
    import tensorflow as tf
    global modelo
    modelo = tf.keras.models.load_model("/content/modeloprueba2.h5")
  def predict(self, file_path):
    import numpy as np
    import tensorflow as tf
    from tensorflow import keras
    img = tf.keras.preprocessing.image.load_img(str(file_path), target_size=(250, 250))
    img_array = tf.keras.preprocessing.image.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0)  
    score = modelo(img_array)[0]
    if score >=0.5:
      return 1
    elif score < 0.5:
      return 0
    #print(modelo(img_array))
    #print(score)
    #return(np.argmax(score))